#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 13.09.2021 11:03
# Generated By: robin.cantone
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$Frm_task_added = New-Object System.Windows.Forms.Form
$comboBox1 = New-Object System.Windows.Forms.ComboBox
$Btn_added_successfully = New-Object System.Windows.Forms.Button
$Lbl_task_successful = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Btn_added_successfully_OnClick= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$Frm_task_added.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 326
$System_Drawing_Size.Width = 327
$Frm_task_added.ClientSize = $System_Drawing_Size
$Frm_task_added.DataBindings.DefaultDataSourceUpdateMode = 0
$Frm_task_added.Name = "Frm_task_added"
$Frm_task_added.Text = "Backup routine added successfully"

$comboBox1.AutoCompleteMode = 1
$comboBox1.AutoCompleteSource = 256
$comboBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$comboBox1.DropDownStyle = 2
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 22
$System_Drawing_Point.Y = 105
$comboBox1.Location = $System_Drawing_Point
$comboBox1.Name = "comboBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 121
$comboBox1.Size = $System_Drawing_Size
$comboBox1.TabIndex = 2
$comboBox1.Visible = $False

$Frm_task_added.Controls.Add($comboBox1)


$Btn_added_successfully.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 240
$System_Drawing_Point.Y = 93
$Btn_added_successfully.Location = $System_Drawing_Point
$Btn_added_successfully.Name = "Btn_added_successfully"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Btn_added_successfully.Size = $System_Drawing_Size
$Btn_added_successfully.TabIndex = 1
$Btn_added_successfully.Text = "OK"
$Btn_added_successfully.UseVisualStyleBackColor = $True
$Btn_added_successfully.add_Click($Btn_added_successfully_OnClick)

$Frm_task_added.Controls.Add($Btn_added_successfully)

$Lbl_task_successful.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 22
$System_Drawing_Point.Y = 29
$Lbl_task_successful.Location = $System_Drawing_Point
$Lbl_task_successful.Name = "Lbl_task_successful"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 225
$Lbl_task_successful.Size = $System_Drawing_Size
$Lbl_task_successful.TabIndex = 0
$Lbl_task_successful.Text = "Backup routine added successfully!"

$Frm_task_added.Controls.Add($Lbl_task_successful)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Frm_task_added.WindowState
#Init the OnLoad event to correct the initial state of the form
$Frm_task_added.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Frm_task_added.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
